---
- name: "install asdf"
  git:
    repo: "https://github.com/asdf-vm/asdf"
    dest: "/home/{{ deployer }}/.asdf"
    update: yes
  remote_user: "{{deployer}}"


- name: "source asdf in bashrc"
  lineinfile:
    dest: "/home/{{ deployer }}/.bash_profile"
    create: yes
    line: "source /home/{{ deployer }}/.asdf/asdf.sh"
  remote_user: "{{deployer}}"


- name: "add asdf plugins"
  command: "bash -lc 'asdf plugin-add {{item}} https://github.com/asdf-vm/asdf-{{item}}.git'"
  with_items:
    - nodejs
    - erlang
    - elixir
  remote_user: "{{deployer}}"
  ignore_errors: yes


- name: "bootstrap nodejs trust"
  command: "bash -lc '~/.asdf/plugins/nodejs/bin/import-release-team-keyring'"
